# ./ios/fastlane/Fastfile
require 'dotenv/load'

# .env 파일 로드 (프로젝트 루트에서)
Dotenv.load('../.env')

default_platform(:ios)

platform :ios do
  # 배포 전 모든 작업이 이뤄지는 곳
  before_all do
    # App Store Connect API Key로 인증 (가장 안전한 방법)
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"], # key 파일 내용을 직접 넣거나 key_filepath 사용
      is_key_content_base64: true
    )
  end

  desc "Flutter 앱을 빌드하고 TestFlight에 배포합니다."
  lane :deploy_to_testflight do
    # 1. Flutter 빌드 (절대 경로 사용)
    sh "cd .. && flutter build ipa --release --export-options-plist=#{File.expand_path('../ExportOptions.plist', Dir.pwd)}"

    # 2. TestFlight 업로드
    pilot(
      ipa: "../build/ios/ipa/soi.ipa", # 생성된 ipa 파일 경로 (프로젝트에 맞게 수정)
      app_identifier: "com.newdawn.soi-project", # 앱 번들 ID
      skip_waiting_for_build_processing: true, # 빌드 처리 대기 없이 바로 다음 단계로 진행
      changelog: "이번 버전의 테스트 변경 사항입니다. (예: 버그 수정 및 성능 개선)", # What to Test 내용
      groups: ["Internal Testers"] # 빌드를 추가할 테스트 그룹 (선택 사항)
    )
  end
end